name: Shravanthi UM
author: Shravanthi UM
markdown: redcarpet
highlighter: true
baseurl: 
title: Shravanthi UM
description: Travel | Learn | Dream
github: http://www.github.com/shravanthium
twitter: http://www.twitter.com/shravanthium
facebook: http://www.facebook.com/shravanthimohan
linkedin: http://www.linkedin.com/shravanthium
email: email@shravanthium.com
location: 12.9667° N, 77.5667° E

##Make sure to edit the above fields, especially for disqus.

